openapi: 3.0.0
info:
  version: 1.0.0
  title: Test APIs Featurify
  description: It's a test API
servers:
  - url: http://localhost:8080
    description: Local server
tags:
  - name: Documentation
    description: It's a all documentation
paths:
  /login:
    get:
      description: ''
      responses:
        default:
          description: ''
  /callback:
    get:
      description: ''
      parameters:
        - name: error
          in: query
          schema:
            type: string
        - name: code
          in: query
          schema:
            type: string
        - name: state
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
  /search:
    get:
      description: ''
      parameters:
        - name: q
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
  /getTrack:
    get:
      description: ''
      parameters:
        - name: q
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
  /audioFeature:
    get:
      description: ''
      parameters:
        - name: q
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
  /tracksRecomendations:
    get:
      description: ''
      parameters:
        - name: limit
          in: query
          schema:
            type: string
        - name: seed_tracks
          in: query
          schema:
            type: string
        - name: seed_artists
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
  /play:
    get:
      description: ''
      parameters:
        - name: uri
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
components:
  schemas:
    Format:
      type: string
      enum:
        - ui
        - json
        - yml
        - yaml
